# Only build on master to prevent redundant builds.
# Build will also be executed on PRs even if not stated here.
branches:
  only:
    - master
sudo: required
git:
  depth: false
matrix:
  include:
    - language: node_js
      node_js:
        - 10.16.0
      before_script:
        - npm install -g @angular/cli
        - npm install
      script:
        - ng build --prod
      # Uncomment once deployment environment is set up.
      # deploy:
      #   provider: script
      #   script: bash docker_push