export enum AuthErrors {
  userNotFound = 'auth/user-not-found',
  wrongPassword = 'auth/wrong-password',
  emailAlreadyInUse = 'auth/email-already-in-use',
  invalidEmail = 'auth/invalid-email',
  weakPassword = 'auth/weak-password',
  userDisabled = 'auth/user-disabled',
  invalidCredential = 'auth/invalid-credential',
  credentialAlreadyInUse = 'auth/credential-already-in-use',
  operationNotAllowed = 'auth/operation-not-allowed',
  invalidUserToken = 'auth/invalid-user-token',
  phoneNumberAlreadyInUse = 'auth/phone-number-already-in-use',
  invalidPhoneNumber = 'auth/invalid-phone-number',
  sessionExpired = 'auth/session-expired',
  invalidVerificationCode = 'auth/invalid-verification-code',
  appNotAuthorized = 'auth/app-not-authorized',
  requiresRecentLogin = 'auth/requires-recent-login',
  userMismatch = 'auth/user-mismatch',
  providerAlreadyLinked = 'auth/provider-already-linked',
  credentialNotFound = 'auth/credential-not-found',
  tooManyRequests = 'auth/too-many-requests',
}
